import type { Metadata } from "next";
import "./globals.css";

import { Bebas_Neue, Mulish } from "next/font/google";
const bbne = Bebas_Neue({ weight: "400" });
const mulish = Mulish({});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bbne.className} ${mulish.className}`}>
        {children}
      </body>
    </html>
  );
}
