import type { Metadata } from "next";
import "./globals.css";
import { ProfileModal } from "@/ui/component/ProfileModal";
import { Bebas_Neue, Mulish } from "next/font/google";

const bbne = Bebas_Neue({ subsets: ["latin"], weight: "400" });
const mulish = Mulish({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bbne.className} ${mulish.className}`}>
        {}
        {children}

        {}
        <ProfileModal />
      </body>
    </html>
  );
}
