import type { Metadata } from "next";
import "./globals.css";

import { Bebas_Neue, Mulish } from "next/font/google";
import { TooltipProvider } from "@/ui/tooltip";
import { SidebarProvider } from "@/ui/sidebar";
const bbne = Bebas_Neue({ weight: "400" });
const mulish = Mulish({});

export const metadata: Metadata = {
  title: "CinaGloria",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${bbne.className} ${mulish.className}`}>
        <TooltipProvider>{children}</TooltipProvider>
      </body>
    </html>
  );
}
