
export const TYPES = {
  NotificationStore: Symbol.for("NotificationStore"),
  UserState: Symbol.for("UserState"),
  LoadState: Symbol.for("LoadState"),
  WsSocket: Symbol.for("WsSocket"),
  JWTChangeRequest: Symbol.for("JWTChangeRequest"),
  GetWsTokenRequest: Symbol.for("GetWsTokenRequest"),
  RequestMe: Symbol.for("RequestMe"),
  RequestPutAdditionData: Symbol.for("RequestPutAdditionData"),
  RequestRegistartion: Symbol.for("RequestRegistartion"),
  RequestConfirm: Symbol.for("RequestConfirm"),
  RequestLoginWithGoogle: Symbol.for("RequestLoginWithGoogle"),
  ReadedRequest: Symbol.for("ReadedRequest"),
  OldNotificationPageRequest: Symbol.for("OldNotificationPageRequest"),
  ReadAllRequest: Symbol.for("ReadAllRequest"),
  LogoutRequest: Symbol.for("LogoutRequest"),
  UploadFileToAServerRequest: Symbol.for("UploadFileToAServerRequest"),
  ChangeAvatarRequest: Symbol.for("ChangeAvatarRequest"),
  ChangeUsernameRequest: Symbol.for("ChangeUsernameRequest"),
  CreateCompetitionRequest: Symbol.for("CreateCompetitionRequest"),
  CompetitionState: Symbol.for("CompetitionState"),
  GetPublicCompetitionRequest: Symbol.for("GetPublicCompetitionRequest"),
  GetPrivateCompetitionRequest: Symbol.for("GetPrivateCompetitionRequest"),
  AuthCheck: Symbol.for("AuthCheck"),
  GetCompetionByIdRequest: Symbol.for("GetCompetionByIdRequest"),
  AdminCheck: Symbol.for("AdminCheck"),
  RequestGetUsers: Symbol.for("RequestGetUsers"),
  AdminCompetitionStore: Symbol.for("AdminCompetitionStore"),
} as const;
